### ISSUE TITLE
BadParcelableException: ClassNotFoundException for PendingCallback

### ISSUE THREAD

**Issue by SUPERCILEX** [firebase/firebase-jobdispatcher-android#72]
```
12-19 17:25:22.014 18473-18473/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.supercilex.robotscouter, PID: 18473
                                                   java.lang.RuntimeException: Unable to start service com.firebase.jobdispatcher.GooglePlayReceiver@61e66f2 with Intent { act=com.google.android.gms.gcm.ACTION_TASK_READY cmp=com.supercilex.robotscouter/com.firebase.jobdispatcher.GooglePlayReceiver (has extras) }: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.gms.gcm.PendingCallback
                                                       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3343)
                                                       at android.app.ActivityThread.-wrap21(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1582)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                    Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.gms.gcm.PendingCallback
                                                       at android.os.Parcel.readParcelableCreator(Parcel.java:2536)
                                                       at android.os.Parcel.readParcelable(Parcel.java:2462)
                                                       at android.os.Parcel.readValue(Parcel.java:2365)
                                                       at android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
                                                       at android.os.BaseBundle.unparcel(BaseBundle.java:269)
                                                       at android.os.Bundle.getParcelable(Bundle.java:864)
                                                       at com.firebase.jobdispatcher.GooglePlayReceiver.a(Unknown Source)
                                                       at com.firebase.jobdispatcher.GooglePlayReceiver.onStartCommand(Unknown Source)
                                                       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3326)
                                                       at android.app.ActivityThread.-wrap21(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1582) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by ciarand** [comment]
This should be fixed by #74. I've cut [`0.5.2`](https://github.com/firebase/firebase-jobdispatcher-android/releases/tag/0.5.2) and pushed it to JCenter.

**Comment by SUPERCILEX** [comment]
@ciarand Thanks! I can confirm that the bug is fixed in production.

**Comment by ciarand** [comment]
Cool, thanks for confirming!

**Comment by Cataalinn** [comment]
In `0.8.1` is still there:

`09-18 13:28:31.396 11943-11995/? E/Parcel: Class not found when unmarshalling: .notifications.services.NotificationMessages
                                           java.lang.ClassNotFoundException: .notifications.services.NotificationMessages
                                               at java.lang.Class.classForName(Native Method)
                                               at java.lang.Class.forName(Class.java:453)
                                               at android.os.Parcel.readParcelableCreator(Parcel.java:2818)
                                               at android.os.Parcel.readParcelable(Parcel.java:2772)
                                               at android.os.Parcel.readValue(Parcel.java:2675)
                                               at android.os.Parcel.readArrayMapInternal(Parcel.java:3042)
                                               at android.os.BaseBundle.unparcel(BaseBundle.java:257)
                                               at android.os.BaseBundle.getString(BaseBundle.java:1086)
                                               at suv.<init>(:com.google.android.gms@11509470:16)
                                               at suv.<init>(:com.google.android.gms@11509470:3)
                                               at swv.a(:com.google.android.gms@11509470:159)
                                               at sww.handleMessage(:com.google.android.gms@11509470:49)
                                               at android.os.Handler.dispatchMessage(Handler.java:105)
                                               at android.os.Looper.loop(Looper.java:164)
                                               at android.os.HandlerThread.run(HandlerThread.java:65)
                                            Caused by: java.lang.ClassNotFoundException: Didn't find class ".notifications.services.NotificationMessages" on path: DexPathList[[zip file "/system/framework/com.android.location.provider.jar", zip file "/system/framework/com.android.media.remotedisplay.jar", zip file "/data/app/com.google.android.gms--oSTMvCl379UMnXE-vZQ2Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.gms--oSTMvCl379UMnXE-vZQ2Q==/lib/x86, /system/fake-libs, /data/app/com.google.android.gms--oSTMvCl379UMnXE-vZQ2Q==/base.apk!/lib/x86, /system/lib, /system/vendor/lib]]
                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                               at java.lang.Class.classForName(Native Method) 
                                               at java.lang.Class.forName(Class.java:453) 
                                               at android.os.Parcel.readParcelableCreator(Parcel.java:2818) 
                                               at android.os.Parcel.readParcelable(Parcel.java:2772) 
                                               at android.os.Parcel.readValue(Parcel.java:2675) 
                                               at android.os.Parcel.readArrayMapInternal(Parcel.java:3042) 
                                               at android.os.BaseBundle.unparcel(BaseBundle.java:257) 
                                               at android.os.BaseBundle.getString(BaseBundle.java:1086) 
                                               at suv.<init>(:com.google.android.gms@11509470:16) 
                                               at suv.<init>(:com.google.android.gms@11509470:3) 
                                               at swv.a(:com.google.android.gms@11509470:159) 
                                               at sww.handleMessage(:com.google.android.gms@11509470:49) 
                                               at android.os.Handler.dispatchMessage(Handler.java:105) 
                                               at android.os.Looper.loop(Looper.java:164) 
                                               at android.os.HandlerThread.run(HandlerThread.java:65) 
09-18 13:28:31.396 11943-11995/? E/AndroidRuntime: FATAL EXCEPTION: netscheduler-queue-handler
                                                   Process: com.google.android.gms.persistent, PID: 11943
                                                   android.os.BadParcelableException: ClassNotFoundException when .notifications.services.NotificationMessages
                                                       at android.os.Parcel.readParcelableCreator(Parcel.java:2846)
                                                       at android.os.Parcel.readParcelable(Parcel.java:2772)
                                                       at android.os.Parcel.readValue(Parcel.java:2675)
                                                       at android.os.Parcel.readArrayMapInternal(Parcel.java:3042)
                                                       at android.os.BaseBundle.unparcel(BaseBundle.java:257)
                                                       at android.os.BaseBundle.getString(BaseBundle.java:1086)
                                                       at suv.<init>(:com.google.android.gms@11509470:16)
                                                       at suv.<init>(:com.google.android.gms@11509470:3)
                                                       at swv.a(:com.google.android.gms@11509470:159)
                                                       at sww.handleMessage(:com.google.android.gms@11509470:49)
                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.os.HandlerThread.run(HandlerThread.java:65)`

**Comment by gotama** [comment]
0.8.5 still an issue 

Refactored class to be Serializable, Parcelable and even used the Parcel lib but still same error.
